---
# this comment is a also hack
version: "3.8"
services:
  tautulli:
    image: tautulli/tautulli:v2.13.4
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/tautulli/config:/config
    ports:
      - 8181:8181
    restart:  unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
